//yoga Product reduser
export let GETALLTPRODUCTS="GETALLTPRODUCTS"
export let DELETEPRODUCTBYID="DELETEPRODUCTBYID"
export let UPDATEPRODUCT="UPDATEPRODUCT"
export let GETPRODUCTBYID="GETPRODUCTBYID"
export let GETPRODUCTBYCATEGORY="GETPRODUCTBYCATEGORY"
export let ADDPRODUCT="ADDPRODUCT"
// prodcut reduser 
export let GETALLTSHIRTS="GETALLTSHIRTS"
export let GETALLHOODIES="GETALLHOODIES"
export let GETALLMUGS="GETALLMUGS"
export let GETALLSTCIKERS="GETALLSTCIKERS"

//user reduser

export let SETUSER="SETUSER"

//cart reduser

export let ADD="ADD"
export let CLEAR="CLEAR"
export let REMOVE="REMOVE"